{{- if not .Values.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "documentation-reader-mcp.fullname" . }}
  labels:
    {{- include "documentation-reader-mcp.labels" . | nindent 4 }}
type: Opaque
stringData:
  GITHUB_TOKEN: {{ .Values.secrets.GITHUB_TOKEN | quote }}
  GITLAB_TOKEN: {{ .Values.secrets.GITLAB_TOKEN | quote }}
{{- end }}
